# -*- coding: utf-8 -*-
"""stemming_and_lemmatization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ostS42I8aYGd28ehEr2Xp8Fa8bzs2NH0
"""

from nltk.stem import PorterStemmer
pstemmer = PorterStemmer()
pstemmer.stem("running")

words_test =["go","went","gone","going"]
for word in words_test:
  print("{} stemmed into {}".format(word,pstemmer.stem(word)))

from nltk.stem import LancasterStemmer
lstemmer = LancasterStemmer()
words_test =["give","gave","given","giving"]
for word in words_test:
   print("{} stemmed into {}".format(word,lstemmer.stem(word)))

from nltk.stem import SnowballStemmer
snowstemmer = SnowballStemmer(language="english")
word_list = ["friend", "friendly","truly","friendship", "friends", "friendships","stabil","destabilize","misunderstanding","railroad","moonlight","football"]
print("{0:20}{1:30}{2:30}{3:30}".format("Word","PorterStemmer","LancasterStemmer","SnowballStemmer"))
for word in word_list:
  print("{0:20}{1:30}{2:30}{3:30}".format(word,pstemmer.stem(word),lstemmer.stem(word),snowstemmer.stem(word)))

# import nltk
from nltk.stem import wordnet
from nltk.stem import WordNetLemmatizer
wnlemmatizer = WordNetLemmatizer()
wnlemmatizer.lemmatize("gave","v")

words_test =["go","went","gone","going"]
for word in words_test:
  print("{} Lemmatized into {}".format(word,wnlemmatizer.lemmatize(word,"v")))

wnlemmatizer.lemmatize("corpora","n")